trigger:
- main

pool:
  name: 'Self-Hosted-Pool'
  demands:
    - agent.name -equals RAVAN

variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildJob
  timeoutInMinutes: 60
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      echo "Current Directory: $(System.DefaultWorkingDirectory)"
      echo "Listing contents of current directory:"
      dir
      echo "Changing directory to MyWebApp"
      cd MyWebApp
      echo "Listing contents of MyWebApp directory:"
      dir
      echo "Running dotnet restore..."
      dotnet restore
      echo "Running dotnet build..."
      dotnet build --configuration $(buildConfiguration)
    displayName: 'Restore and Build'

  - script: |
      cd MyWebApp
      echo "Running dotnet publish..."
      dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    displayName: 'Publish Artifact'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
